version: '3'
services:
 nginx:
   image: nginx:1-alpine
   depends_on:
     - web
   volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   ports:
     - "8083:80"
 web:
   build: .
   command: bash server.sh
   env_file:
     - .env
   volumes:
     - ./flag_djang0_p1ckle:/flag_djang0_p1ckle
